CONFIRM_CODE = '//span[@style="color:#CE210F; "]/text()'
BASE = '//*[@id="backgroundTable"]/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody'
FLIGHT_NUM = '//td[contains(@style, "background-color: #172E4D;")]/text()'
ITINERARY = '//tr[@style="text-align: left; font-family: Arial,sans-serif;"]//td/text()'
GUEST = BASE + '/tr[28]//td/text()'
BAGGAGE_NAMES = BASE + '/tr[37]/td/table[1]//td/text()'
BAGGAGE_VALUES = BASE + '/tr[37]/td/table[2]//*/text()'
AIRLINE_LINK = '//ul/li/a/@href'
AIRLINE_TEXT = '//ul/li/a/text()'
DISABILITY_ASSISTANCE = BASE + '/tr[50]/td/text()'
PAYMENT = BASE + '/tr[60]/td/table/tbody/tr'
CHANGE_LINKS = BASE + '/tr/td/a/@href'
LINKS = '//*[@id="backgroundTable"]/tbody/tr/td/table/tbody/tr[6]//a'
