CHANGE_LINK = '//a[@class="brand-button"]/@href'
NAME = '//td[@id="hotel-name"]/span/text()'
ADDRESS = '//td[@id="hotel-address"]/span/text()'
LINK = '//table[@id="hotel-name-and-info-section"]/tr[3]/td/table/tr/td/a/@href'
RESERVATION_DATE = '//table[@id="trip-details-content"]/tr[5]/td/table/tr/td/table/tr[3]/td/table/tr[2]/td/span/text()'
COMFIRM_NUMBER = '//table[@id="trip-details-content"]/tr[5]/td/table/tr/td/table/tr[4]/td/table/tr[2]/td/span/text()'
CHECK_IN_OUT_TIME = '//table[@id="check-in-out-time-section"]/tr/td[@class="split"]/table/tr[2]/td/span/text()'
CHECK_IN_POLICY = '//table[@id="trip-details-content"]/tr[5]/td/table/tr[3]/td/table/tr[3]/td/table/tr/td/span/text()'
GUEST = '//table[@id="trip-details-content"]/tr[5]/td[@class="primary-section"]/table/tr[5]/td/table/tr[2]/td/table/tr/td/table/tr/td/span/text()'
ROOM = '//table[@id="trip-details-content"]/tr[5]/td/table/tr[5]/td/table/tr[3]/td/table/tr/td/table/tr[2]/td/span/text()'
ROOM_REQUEST = '//table[@id="trip-details-content"]/tr[5]/td[@class="primary-section"]/table/tr[5]/td/table/tr[4]/td/div/text()'
PRICE = '//table[@id="trip-details-content"]/tr[5]/td/table/tr[7]/td/table/tr/td/table/tr[2]/td/table/tr[2]/td/span/text()'
TOTAL = '//table[@id="trip-details-content"]/tr[5]/td/table/tr[7]/td/table/tr/td/table/tr[2]/td/table/tr/td/strong/text()'
PRICE_DETAILS = '//table[@id="trip-details-content"]/tr[5]/td/table/tr[7]/td/table/tr/td/table/tr[3]/td/span/text()'
TAXES = '//table[@id="trip-details-content"]/tr[5]/td/table/tr[7]/td/table/tr/td/table/tr[2]/td/table/tr[4]/td/span/text()'

# remove_tags
ADDITIONAL_HOTEL_FEE = '//table[@id="trip-details-content"]/tr[5]/td[@class="primary-section"]/table/tr[9]'
RULES = '//table[@id="trip-details-content"]/tr[5]/td[@class="primary-section"]/table/tr[11]/td/table/tr[2]/td/table/tr/td/span/text()'
HELP = '//table[@id="trip-details-content"]/tr[5]/td[@class="primary-section"]/table/tr[11]/td/table/tr[4]/td/table/tr[2]/td/table/tr[3]/td/span/a/text()'