BASE = '//table[@id="trip-details-content"]/tr[8]/td/table'
DATES = '//table[@id="hotel-name-and-info-section"]/tr[1]/td/div[2]/text()'
ITINERARY = '//table[@id="hotel-name-and-info-section"]/tr[2]/td/div[2]/p/text()'
CONFIRM_NUM = BASE + '/tr[2]/td/table[1]/tr[4]//div[@class="content-text"]/text()'
BOOKING_ID = BASE + '/tr[2]/td/table[1]/tr[5]//div[@class="content-text"]/text()'
TICKET = BASE + '/tr[2]/td/table[1]/tr[6]//div[@class="content-text"]/text()'
RELATED_LINK_1 = BASE + '/tr[7]/td/table//a'
CANCELLATION = BASE + '/tr[2]/td/table[2]/tr[1]/td/span/text()'
FLIGHT_NAME = BASE + '/tr[2]/td/table[3]/tr[3]/td/span/text()'
DEPART_STATION = '//table[@id="check-in-out-time-section"]/tr/td[1]/table/tr[1]/td/div/text()'
DEPART_TIME = '//table[@id="check-in-out-time-section"]/tr/td[1]/table/tr[2]/td/span/text()'
DEPART_TERMINAL = '//table[@id="check-in-out-time-section"]/tr/td[1]/table/tr[3]/td/span/span/text()'
ARRIVE_STATION = '//table[@id="check-in-out-time-section"]/tr/td[3]/table/tr[1]/td/div/text()'
ARRIVE_TIME = '//table[@id="check-in-out-time-section"]/tr/td[3]/table/tr[2]/td/span/text()'
ARRIVE_TERMINAL = '//table[@id="check-in-out-time-section"]/tr/td[3]/table/tr[3]/td/p/span/text()'
FARE_TYPE = BASE + '/tr[2]/td/table[3]/tr[5]//a/text()'
CABIN = BASE + '/tr[2]/td/table[3]/tr[6]/td/span/span/text()'
FLIGHT_INFO_DIVS = BASE + '/tr[2]/td/table[3]/tr[7]/td/div'
FLIGHT_INFO_DIV_NAME = './span/strong/text()'
FLIGHT_INFO_DIV_VALUE = './ul/span/li/text()'
FLIGHT_DURATION = BASE + '/tr[2]/td/table[4]/tr[3]/td/span/text()'
GUEST = BASE + '/tr[3]/td/table/tr[3]/td/div[1]/text()'
PRICE = BASE + '/tr[4]/td/table/tr/td/table/tr[3]/td/div/span/text()'
TOTAL = '//div[@id="total"]/span[2]/strong/text()'
UNITED_RESTRICTIONS = BASE + '/tr[6]/td/table/tr[3]/td/div/ul/li'
UNITED_RESTRICTIONS_DES = BASE + '/tr[6]/td/table/tr[3]/td/div/ol/li/small/text()'
NOTICE = BASE + '/tr[6]/td/table/tr[7]/td/div/text()'
AIRLINE_RULE = BASE + '/tr[6]/td/table/tr[5]/td/div[2]/text()'
RELATED_LINK_2 = BASE + '/tr[6]/td/table//a/@href'
RELATED_TEXT_2 = BASE + '/tr[6]/td/table//a/text()'
PHONE = BASE + '/tr[7]/td/table/tr[5]/td/div[1]/text()'