CONFIRM_NUM = '//td[@class="padt10m padb10m"][1]/table/tr/td[1]/text()'
HOTEL_NAME = '//td[@class="h1m centerm"][1]/text()'
ADDRESS = '//td[@class="borderr0m"][1]/table/tr/td[2]/text()'
PHONE = '//td[@class="padt10m"][1]/table/tr/td[2]/text()'
CHECK_IN_OUT_DATETIME = '//td[@class="centerm"]/text()'
RELATED_LINKS = '//table[@class="w80m"]//a/@href'
RELATED_LINKS_TEXT = '//table[@class="w80m"]//a/text()'
PLAN_TEXT = '/html/body/table/tr/td/table/tr/td/table[3]/tr/td/table/tr/td/table/tr[7]//a/text()'
PLAN_LINK = '/html/body/table/tr/td/table/tr/td/table[3]/tr/td/table/tr/td/table/tr[7]//a/@href'
RESERVATION_INFO = '//table[@class="padb5m"]/tr/td'