NAME = '//a[@id="restaurant-name"]/span/text()'
NAME_LINK = '//a[@id="restaurant-name"]/@href'
DATETIME = '//span[@id="reservation-datetime"]/text()'
USER_NAME = '//span[@id="reservation-diner-name"]/text()'
CONFIRMATION_NUMBER = '//span[@id="reservation-confirmationNumber"]/text()'
MENU = '//a[@id="see-menu"]/@href'
DIRECTION = '//a[@id="get-directions"]/@href'
ADDRESS = '//td[@class="content-block align-center restaurant-address-td"]/span/text()'
PHONE = '//td[@class="content-block align-center restaurant-telephone-td"]/span/text()'
PROMOTED_OFFER_TITLE = '//span[@id="offer-title"]/text()'
PROMOTED_OFFER_DETAILS = '//span[@id="offer-description"]/text()'
PROMOTED_OFFER_CONDITIONS = '//span[@id="offer-terms-and-conditions"]/text()'
LINK = '//td[@class="booking-cta-td"]/a/@href'
LINK_NAME = '//td[@class="booking-cta-td"]/a/span/text()'
RESTAURANT_CONFIRMATION = '//div[@id="restaurant-messages-confirmation"]/text()'
RESTAURANT_DETAILS = '//div[@id="restaurant-messages-details"]/b/text()'
NOTE = '//div[@id="restaurant-messages-details"]/text()'
SPECIAL_NOTE = '//span[@id="reservation-notes"]/text()'
