HOTEL_NAME = '//table/tr[10]/td/table/tr/td[1]/b/text()'
ADDRESS = '//table/tr[10]/td/table/tr/td[1]/span/text()'
PHONE = '//table/tr[10]/td/table/tr/td[1]/a[starts-with(@href, "tel:")]/text()'
WEBSITE = '//table/tr[10]/td/table/tr/td[1]/a[text()="Hotel Website"]/@href'
NAME_CODE = '/html/body/table/tr[12]/td/text()'
DATE = '//table/tr[14]/td/table/tr[1]/td[2]/text()'
GUEST_NUM = '//table/tr[14]/td/table/tr[2]/td[2]/text()'
ROOMTYPE_PRICE = '/html/body/table[1]/tr[14]/td/text()'
PAYMENT = '//table[1]/tr[16]/td/table/tr'
CANCEL_LINK = '//table[1]/tr[20]//a/@href'
CONTACT = '//table[@style="line-height:16px"]/tr/td[2]'