GUEST_NAME = '//strong[contains(@style, "#f99f24;")][1]/text()'
CONFIRM_NUM = '//span[contains(@style, "color:#f99f24;")]/text()'
HOTEL_NAME = '//td[@style="padding-bottom:10.0px;color:#666666;font-size:13.0px;font-family:Arial,Helvetica,sans-serif;"]/strong/text()'
ADDRESS = '//td[@style="padding-bottom:10.0px;color:#666666;font-size:13.0px;font-family:Arial,Helvetica,sans-serif;"]/text()'
HOTEL_LINK = '//a[text()="Hotel Website"]/@href'
EMAIL = '//a[text()="Hotel Email"]/@href'
MODIFY_LINK = '//td[@bgcolor="#fefce8"]//a[text()="Modify Reservation"]/@href'
CANCEL_LINK = '//td[@bgcolor="#fefce8"]//a[text()="Cancel Reservation"]/@href'
RESERVATION = '//td[@bgcolor="#fefce8"]/text()'
PRICE = '//table[contains(@style, "#cccccc solid 1.0px;")]/tbody/tr'
OTHER_INFO = '//td[@style="padding-top:20.0px;padding-bottom:23.0px;padding-left:10.0px;padding-right:10.0px;color:#3b3b3b;font-size:10.0px;font-family:Arial,Helvetica,sans-serif;color:#666666;"]/text()'
