HOTEL_NAME_CH = '//*[@id="HEADING"]/text()'
HOTEL_NAME_EN = '//*[@id="HEADING"]/div/text()'
LOST_DESC = '//*[@class="partialMatchInfoContainer "]//text()'
# STAR_LEVEL = '//*[@id="HEADING"]/div/text()'
COMMENT_LEVLE = '//*[@class="hotels-hotel-review-overview-Reviews__rating--1sqat"]/span[1]//text()'  # 评论等级
HOTEL_FACILITY = '//div[contains(@class,"is-6-mobile")and contains(@class,"ui_column")]//*[@class="textitem"]//text()'
ADDRESS = '//div[contains(@class,"is-hidden-mobile") and contains(@class,"address")and contains(@class,"ui_link_container")]/span[2]//text()'
PRICE = '//div[contains(@class,"priceBlock") and contains(@class,"ui_column")and contains(@class,"is-12-tablet")]/div/div/text()'
HOTEL_URL = '//a[contains(@class,"property_title")and contains(@class,"prominent")]/@href'
HOTEL_NAME = '//a[contains(@class,"property_title")and contains(@class,"prominent")]/text()'
HOTEL_EN_NAME = '//a[contains(@class,"property_title")and contains(@class,"prominent")]/@href'
BOOKING_NAME = '//a[contains(@class,"hotel_name_link")and contains(@class,"url")]/span//text()'
BOOKING_URL = '//a[contains(@class,"hotel_name_link")and contains(@class,"url")]//@href'
PHONE = '//span[contains(@class,"is-hidden-mobile")and contains(@class,"ui_link")and contains(@class,"detail")and contains(@class," level_4 ")]//text()'
