# encoding=utf-8
import re

ll = '''
<ul class="more clear" data-reactid="20"><li data-reactid="21"><a class="" href="http://lb.meituan.com/meishi/c393/" data-reactid="22">代金券</a></li><li data-reactid="23"><a class="" href="http://lb.meituan.com/meishi/c11/" data-reactid="24">蛋糕甜点</a></li><li data-reactid="25"><a class="" href="http://lb.meituan.com/meishi/c17/" data-reactid="26">火锅</a></li><li data-reactid="27"><a class="" href="http://lb.meituan.com/meishi/c40/" data-reactid="28">自助餐</a></li><li data-reactid="29"><a class="" href="http://lb.meituan.com/meishi/c36/" data-reactid="30">小吃快餐</a></li><li data-reactid="31"><a class="" href="http://lb.meituan.com/meishi/c28/" data-reactid="32">日韩料理</a></li><li data-reactid="33"><a class="" href="http://lb.meituan.com/meishi/c35/" data-reactid="34">西餐</a></li><li data-reactid="35"><a class="" href="http://lb.meituan.com/meishi/c395/" data-reactid="36">聚餐宴请</a></li><li data-reactid="37"><a class="" href="http://lb.meituan.com/meishi/c54/" data-reactid="38">烧烤烤肉</a></li><li data-reactid="39"><a class="" href="http://lb.meituan.com/meishi/c20003/" data-reactid="40">东北菜</a></li><li data-reactid="41"><a class="" href="http://lb.meituan.com/meishi/c55/" data-reactid="42">川湘菜</a></li><li data-reactid="43"><a class="" href="http://lb.meituan.com/meishi/c56/" data-reactid="44">江浙菜</a></li><li data-reactid="45"><a class="" href="http://lb.meituan.com/meishi/c20004/" data-reactid="46">香锅烤鱼</a></li><li data-reactid="47"><a class="" href="http://lb.meituan.com/meishi/c57/" data-reactid="48">粤菜</a></li><li data-reactid="49"><a class="" href="http://lb.meituan.com/meishi/c58/" data-reactid="50">西北菜</a></li><li data-reactid="51"><a class="" href="http://lb.meituan.com/meishi/c59/" data-reactid="52">京菜鲁菜</a></li><li data-reactid="53"><a class="" href="http://lb.meituan.com/meishi/c41/" data-reactid="54">咖啡酒吧</a></li><li data-reactid="55"><a class="" href="http://lb.meituan.com/meishi/c60/" data-reactid="56">云贵菜</a></li><li data-reactid="57"><a class="" href="http://lb.meituan.com/meishi/c62/" data-reactid="58">东南亚菜</a></li><li data-reactid="59"><a class="" href="http://lb.meituan.com/meishi/c63/" data-reactid="60">海鲜</a></li><li data-reactid="61"><a class="" href="http://lb.meituan.com/meishi/c217/" data-reactid="62">素食</a></li><li data-reactid="63"><a class="" href="http://lb.meituan.com/meishi/c227/" data-reactid="64">台湾/客家菜</a></li><li data-reactid="65"><a class="" href="http://lb.meituan.com/meishi/c228/" data-reactid="66">创意菜</a></li><li data-reactid="67"><a class="" href="http://lb.meituan.com/meishi/c229/" data-reactid="68">汤/粥/炖菜</a></li><li data-reactid="69"><a class="" href="http://lb.meituan.com/meishi/c232/" data-reactid="70">蒙餐</a></li><li data-reactid="71"><a class="" href="http://lb.meituan.com/meishi/c233/" data-reactid="72">新疆菜</a></li><li data-reactid="73"><a class="" href="http://lb.meituan.com/meishi/c24/" data-reactid="74">其他美食</a></li></ul>
<ul class="more clear" data-reactid="20"><li data-reactid="21"><a class="" href="http://bj.meituan.com/meishi/c393/" data-reactid="22">代金券</a></li><li data-reactid="23"><a class="" href="http://bj.meituan.com/meishi/c11/" data-reactid="24">蛋糕甜点</a></li><li data-reactid="25"><a class="" href="http://bj.meituan.com/meishi/c17/" data-reactid="26">火锅</a></li><li data-reactid="27"><a class="" href="http://bj.meituan.com/meishi/c40/" data-reactid="28">自助餐</a></li><li data-reactid="29"><a class="" href="http://bj.meituan.com/meishi/c36/" data-reactid="30">小吃快餐</a></li><li data-reactid="31"><a class="" href="http://bj.meituan.com/meishi/c28/" data-reactid="32">日韩料理</a></li><li data-reactid="33"><a class="" href="http://bj.meituan.com/meishi/c35/" data-reactid="34">西餐</a></li><li data-reactid="35"><a class="" href="http://bj.meituan.com/meishi/c395/" data-reactid="36">聚餐宴请</a></li><li data-reactid="37"><a class="" href="http://bj.meituan.com/meishi/c54/" data-reactid="38">烧烤烤肉</a></li><li data-reactid="39"><a class="" href="http://bj.meituan.com/meishi/c20003/" data-reactid="40">东北菜</a></li><li data-reactid="41"><a class="" href="http://bj.meituan.com/meishi/c55/" data-reactid="42">川湘菜</a></li><li data-reactid="43"><a class="" href="http://bj.meituan.com/meishi/c56/" data-reactid="44">江浙菜</a></li><li data-reactid="45"><a class="" href="http://bj.meituan.com/meishi/c20004/" data-reactid="46">香锅烤鱼</a></li><li data-reactid="47"><a class="" href="http://bj.meituan.com/meishi/c57/" data-reactid="48">粤菜</a></li><li data-reactid="49"><a class="" href="http://bj.meituan.com/meishi/c400/" data-reactid="50">中式烧烤/烤串</a></li><li data-reactid="51"><a class="" href="http://bj.meituan.com/meishi/c58/" data-reactid="52">西北菜</a></li><li data-reactid="53"><a class="" href="http://bj.meituan.com/meishi/c41/" data-reactid="54">咖啡酒吧</a></li><li data-reactid="55"><a class="" href="http://bj.meituan.com/meishi/c60/" data-reactid="56">云贵菜</a></li><li data-reactid="57"><a class="" href="http://bj.meituan.com/meishi/c62/" data-reactid="58">东南亚菜</a></li><li data-reactid="59"><a class="" href="http://bj.meituan.com/meishi/c63/" data-reactid="60">海鲜</a></li><li data-reactid="61"><a class="" href="http://bj.meituan.com/meishi/c217/" data-reactid="62">素食</a></li><li data-reactid="63"><a class="" href="http://bj.meituan.com/meishi/c227/" data-reactid="64">台湾/客家菜</a></li><li data-reactid="65"><a class="" href="http://bj.meituan.com/meishi/c228/" data-reactid="66">创意菜</a></li><li data-reactid="67"><a class="" href="http://bj.meituan.com/meishi/c229/" data-reactid="68">汤/粥/炖菜</a></li><li data-reactid="69"><a class="" href="http://bj.meituan.com/meishi/c232/" data-reactid="70">蒙餐</a></li><li data-reactid="71"><a class="" href="http://bj.meituan.com/meishi/c233/" data-reactid="72">新疆菜</a></li><li data-reactid="73"><a class="" href="http://bj.meituan.com/meishi/c24/" data-reactid="74">其他美食</a></li><li data-reactid="75"><a class="" href="http://bj.meituan.com/meishi/c59/" data-reactid="76">京菜鲁菜</a></li></ul>


'''
url = 'https://lb.meituan.com/meishi/'
re_url = "(" + url + "c\d+/)"
print(re_url)

result = re.findall('"(http://.*?.meituan.com/meishi/c\d+/)"', ll)  # 针对不同的城市都可提取出来

# print(result)

areas = '''[{"id": 14, "name": "朝阳区", "url": "http://bj.meituan.com/meishi/b14/",
          "subAreas": [{"id": 14, "name": "全部", "url": "http://bj.meituan.com/meishi/b14/"},
                       {"id": 1162, "name": "大望路", "url": "http://bj.meituan.com/meishi/b1162/"},
                       {"id": 1472, "name": "双井", "url": "http://bj.meituan.com/meishi/b1472/"},
                       {"id": 1759, "name": "北苑家园", "url": "http://bj.meituan.com/meishi/b1759/"},
                       {"id": 1475, "name": "酒仙桥", "url": "http://bj.meituan.com/meishi/b1475/"},
                       {"id": 675, "name": "安贞", "url": "http://bj.meituan.com/meishi/b675/"},
                       {"id": 1476, "name": "管庄", "url": "http://bj.meituan.com/meishi/b1476/"},
                       {"id": 1478, "name": "十八里店", "url": "http://bj.meituan.com/meishi/b1478/"},
                       {"id": 673, "name": "望京", "url": "http://bj.meituan.com/meishi/b673/"},
                       {"id": 1409, "name": "亮马桥", "url": "http://bj.meituan.com/meishi/b1409/"},
                       {"id": 667, "name": "建外大街", "url": "http://bj.meituan.com/meishi/b667/"},
                       {"id": 668, "name": "朝外大街/世贸天阶", "url": "http://bj.meituan.com/meishi/b668/"},
                       {"id": 670, "name": "左家庄", "url": "http://bj.meituan.com/meishi/b670/"},
                       {"id": 672, "name": "亚运村", "url": "http://bj.meituan.com/meishi/b672/"},
                       {"id": 1203, "name": "四惠", "url": "http://bj.meituan.com/meishi/b1203/"},
                       {"id": 1204, "name": "四惠东", "url": "http://bj.meituan.com/meishi/b1204/"},
                       {"id": 1407, "name": "团结湖/朝阳公园", "url": "http://bj.meituan.com/meishi/b1407/"},
                       {"id": 1410, "name": "三元桥", "url": "http://bj.meituan.com/meishi/b1410/"},
                       {"id": 1411, "name": "太阳宫", "url": "http://bj.meituan.com/meishi/b1411/"},
                       {"id": 1471, "name": "国贸/建外", "url": "http://bj.meituan.com/meishi/b1471/"},
                       {"id": 1473, "name": "三里屯/工体", "url": "http://bj.meituan.com/meishi/b1473/"},
                       {"id": 1474, "name": "对外经贸", "url": "http://bj.meituan.com/meishi/b1474/"},
                       {"id": 1477, "name": "首都机场", "url": "http://bj.meituan.com/meishi/b1477/"},
                       {"id": 1760, "name": "十里堡", "url": "http://bj.meituan.com/meishi/b1760/"},
                       {"id": 1935, "name": "悠唐生活广场", "url": "http://bj.meituan.com/meishi/b1935/"},
                       {"id": 5691, "name": "朝阳大悦城", "url": "http://bj.meituan.com/meishi/b5691/"},
                       {"id": 5973, "name": "东坝", "url": "http://bj.meituan.com/meishi/b5973/"},
                       {"id": 5974, "name": "石佛营", "url": "http://bj.meituan.com/meishi/b5974/"},
                       {"id": 5975, "name": "甜水园", "url": "http://bj.meituan.com/meishi/b5975/"},
                       {"id": 5976, "name": "八里庄", "url": "http://bj.meituan.com/meishi/b5976/"},
                       {"id": 5982, "name": "工体", "url": "http://bj.meituan.com/meishi/b5982/"},
                       {"id": 5983, "name": "百子湾", "url": "http://bj.meituan.com/meishi/b5983/"},
                       {"id": 5984, "name": "传媒大学", "url": "http://bj.meituan.com/meishi/b5984/"},
                       {"id": 5985, "name": "双桥", "url": "http://bj.meituan.com/meishi/b5985/"},
                       {"id": 5986, "name": "北京欢乐谷", "url": "http://bj.meituan.com/meishi/b5986/"},
                       {"id": 5987, "name": "高碑店", "url": "http://bj.meituan.com/meishi/b5987/"},
                       {"id": 5988, "name": "北京东站", "url": "http://bj.meituan.com/meishi/b5988/"},
                       {"id": 5989, "name": "霄云路", "url": "http://bj.meituan.com/meishi/b5989/"},
                       {"id": 5990, "name": "蓝色港湾", "url": "http://bj.meituan.com/meishi/b5990/"},
                       {"id": 5991, "name": "朝阳公园", "url": "http://bj.meituan.com/meishi/b5991/"},
                       {"id": 5992, "name": "燕莎", "url": "http://bj.meituan.com/meishi/b5992/"},
                       {"id": 5993, "name": "农业展览馆", "url": "http://bj.meituan.com/meishi/b5993/"},
                       {"id": 5994, "name": "劲松", "url": "http://bj.meituan.com/meishi/b5994/"},
                       {"id": 5995, "name": "潘家园", "url": "http://bj.meituan.com/meishi/b5995/"},
                       {"id": 7773, "name": "姚家园", "url": "http://bj.meituan.com/meishi/b7773/"},
                       {"id": 8044, "name": "十里河", "url": "http://bj.meituan.com/meishi/b8044/"},
                       {"id": 8045, "name": "立水桥/北苑家园", "url": "http://bj.meituan.com/meishi/b8045/"},
                       {"id": 8046, "name": "小营", "url": "http://bj.meituan.com/meishi/b8046/"},
                       {"id": 8047, "name": "北沙滩", "url": "http://bj.meituan.com/meishi/b8047/"},
                       {"id": 8048, "name": "大屯", "url": "http://bj.meituan.com/meishi/b8048/"},
                       {"id": 12354, "name": "常营", "url": "http://bj.meituan.com/meishi/b12354/"},
                       {"id": 13873, "name": "鸟巢/水立方", "url": "http://bj.meituan.com/meishi/b13873/"},
                       {"id": 14091, "name": "世贸天阶", "url": "http://bj.meituan.com/meishi/b14091/"},
                       {"id": 30855, "name": "草房", "url": "http://bj.meituan.com/meishi/b30855/"},
                       {"id": 31118, "name": "首都机场生活区", "url": "http://bj.meituan.com/meishi/b31118/"},
                       {"id": 31127, "name": "王四营", "url": "http://bj.meituan.com/meishi/b31127/"},
                       {"id": 32504, "name": "霄云路/三元桥", "url": "http://bj.meituan.com/meishi/b32504/"},
                       {"id": 35936, "name": "四惠交通枢纽", "url": "http://bj.meituan.com/meishi/b35936/"},
                       {"id": 37483, "name": "西直河/亦庄", "url": "http://bj.meituan.com/meishi/b37483/"},
                       {"id": 37693, "name": "和平里/国展中心", "url": "http://bj.meituan.com/meishi/b37693/"},
                       {"id": 38771, "name": "孙河", "url": "http://bj.meituan.com/meishi/b38771/"},
                       {"id": 39367, "name": "马泉营", "url": "http://bj.meituan.com/meishi/b39367/"}]},
         {"id": 17, "name": "海淀区", "url": "http://bj.meituan.com/meishi/b17/",
          "subAreas": [{"id": 17, "name": "全部", "url": "http://bj.meituan.com/meishi/b17/"},
                       {"id": 1479, "name": "双榆树", "url": "http://bj.meituan.com/meishi/b1479/"},
                       {"id": 696, "name": "上地", "url": "http://bj.meituan.com/meishi/b696/"},
                       {"id": 1761, "name": "远大路", "url": "http://bj.meituan.com/meishi/b1761/"},
                       {"id": 1480, "name": "五棵松", "url": "http://bj.meituan.com/meishi/b1480/"},
                       {"id": 1098, "name": "魏公村", "url": "http://bj.meituan.com/meishi/b1098/"},
                       {"id": 1481, "name": "清河", "url": "http://bj.meituan.com/meishi/b1481/"},
                       {"id": 692, "name": "北下关", "url": "http://bj.meituan.com/meishi/b692/"},
                       {"id": 688, "name": "中关村", "url": "http://bj.meituan.com/meishi/b688/"},
                       {"id": 689, "name": "五道口", "url": "http://bj.meituan.com/meishi/b689/"},
                       {"id": 695, "name": "航天桥", "url": "http://bj.meituan.com/meishi/b695/"},
                       {"id": 691, "name": "苏州桥", "url": "http://bj.meituan.com/meishi/b691/"},
                       {"id": 697, "name": "颐和园", "url": "http://bj.meituan.com/meishi/b697/"},
                       {"id": 690, "name": "牡丹园/北太平庄", "url": "http://bj.meituan.com/meishi/b690/"},
                       {"id": 693, "name": "公主坟/万寿路", "url": "http://bj.meituan.com/meishi/b693/"},
                       {"id": 694, "name": "紫竹桥", "url": "http://bj.meituan.com/meishi/b694/"},
                       {"id": 1241, "name": "大钟寺", "url": "http://bj.meituan.com/meishi/b1241/"},
                       {"id": 1242, "name": "知春路", "url": "http://bj.meituan.com/meishi/b1242/"},
                       {"id": 5728, "name": "西三旗", "url": "http://bj.meituan.com/meishi/b5728/"},
                       {"id": 5971, "name": "四季青", "url": "http://bj.meituan.com/meishi/b5971/"},
                       {"id": 7772, "name": "香山/植物园", "url": "http://bj.meituan.com/meishi/b7772/"},
                       {"id": 8041, "name": "北京大学", "url": "http://bj.meituan.com/meishi/b8041/"},
                       {"id": 8042, "name": "人民大学", "url": "http://bj.meituan.com/meishi/b8042/"},
                       {"id": 8043, "name": "万柳", "url": "http://bj.meituan.com/meishi/b8043/"},
                       {"id": 8788, "name": "学院路", "url": "http://bj.meituan.com/meishi/b8788/"},
                       {"id": 9021, "name": "北京西站/军博", "url": "http://bj.meituan.com/meishi/b9021/"},
                       {"id": 9177, "name": "农业大学西区", "url": "http://bj.meituan.com/meishi/b9177/"},
                       {"id": 36658, "name": "百望山森林公园/309医院", "url": "http://bj.meituan.com/meishi/b36658/"}]},
         {"id": 20, "name": "丰台区", "url": "http://bj.meituan.com/meishi/b20/",
          "subAreas": [{"id": 20, "name": "全部", "url": "http://bj.meituan.com/meishi/b20/"},
                       {"id": 1097, "name": "洋桥/木樨园", "url": "http://bj.meituan.com/meishi/b1097/"},
                       {"id": 1766, "name": "刘家窑/宋家庄", "url": "http://bj.meituan.com/meishi/b1766/"},
                       {"id": 1484, "name": "北大地/万丰路", "url": "http://bj.meituan.com/meishi/b1484/"},
                       {"id": 705, "name": "方庄/蒲黄榆", "url": "http://bj.meituan.com/meishi/b705/"},
                       {"id": 706, "name": "北京西站/六里桥", "url": "http://bj.meituan.com/meishi/b706/"},
                       {"id": 1767, "name": "青塔", "url": "http://bj.meituan.com/meishi/b1767/"},
                       {"id": 1768, "name": "北京南站/开阳里", "url": "http://bj.meituan.com/meishi/b1768/"},
                       {"id": 1769, "name": "草桥/公益西桥", "url": "http://bj.meituan.com/meishi/b1769/"},
                       {"id": 1770, "name": "看丹桥/新华街", "url": "http://bj.meituan.com/meishi/b1770/"},
                       {"id": 7676, "name": "分钟寺/成寿寺", "url": "http://bj.meituan.com/meishi/b7676/"},
                       {"id": 7677, "name": "夏家胡同/纪家庙", "url": "http://bj.meituan.com/meishi/b7677/"},
                       {"id": 7678, "name": "马家堡/角门", "url": "http://bj.meituan.com/meishi/b7678/"},
                       {"id": 9053, "name": "丽泽桥/丰管路", "url": "http://bj.meituan.com/meishi/b9053/"},
                       {"id": 9597, "name": "大红门", "url": "http://bj.meituan.com/meishi/b9597/"},
                       {"id": 14035, "name": "南苑/东高地", "url": "http://bj.meituan.com/meishi/b14035/"},
                       {"id": 14036, "name": "卢沟桥", "url": "http://bj.meituan.com/meishi/b14036/"},
                       {"id": 14038, "name": "云岗", "url": "http://bj.meituan.com/meishi/b14038/"},
                       {"id": 14040, "name": "花乡/新发地", "url": "http://bj.meituan.com/meishi/b14040/"},
                       {"id": 14043, "name": "世界公园", "url": "http://bj.meituan.com/meishi/b14043/"}]},
         {"id": 16, "name": "西城区", "url": "http://bj.meituan.com/meishi/b16/",
          "subAreas": [{"id": 16, "name": "全部", "url": "http://bj.meituan.com/meishi/b16/"},
                       {"id": 1487, "name": "后海/什刹海", "url": "http://bj.meituan.com/meishi/b1487/"},
                       {"id": 685, "name": "西直门/动物园", "url": "http://bj.meituan.com/meishi/b685/"},
                       {"id": 1485, "name": "西四", "url": "http://bj.meituan.com/meishi/b1485/"},
                       {"id": 1489, "name": "虎坊桥", "url": "http://bj.meituan.com/meishi/b1489/"},
                       {"id": 683, "name": "复兴门", "url": "http://bj.meituan.com/meishi/b683/"},
                       {"id": 1762, "name": "德外大街", "url": "http://bj.meituan.com/meishi/b1762/"},
                       {"id": 700, "name": "广外大街", "url": "http://bj.meituan.com/meishi/b700/"},
                       {"id": 1096, "name": "右安门", "url": "http://bj.meituan.com/meishi/b1096/"},
                       {"id": 682, "name": "西单", "url": "http://bj.meituan.com/meishi/b682/"},
                       {"id": 1765, "name": "菜市口/陶然亭", "url": "http://bj.meituan.com/meishi/b1765/"},
                       {"id": 699, "name": "广内大街", "url": "http://bj.meituan.com/meishi/b699/"},
                       {"id": 684, "name": "阜成门", "url": "http://bj.meituan.com/meishi/b684/"},
                       {"id": 686, "name": "新街口", "url": "http://bj.meituan.com/meishi/b686/"},
                       {"id": 701, "name": "宣武门", "url": "http://bj.meituan.com/meishi/b701/"},
                       {"id": 1488, "name": "牛街", "url": "http://bj.meituan.com/meishi/b1488/"},
                       {"id": 702, "name": "前门/大栅栏", "url": "http://bj.meituan.com/meishi/b702/"},
                       {"id": 1486, "name": "月坛", "url": "http://bj.meituan.com/meishi/b1486/"},
                       {"id": 5981, "name": "地安门", "url": "http://bj.meituan.com/meishi/b5981/"},
                       {"id": 15850, "name": "西便门", "url": "http://bj.meituan.com/meishi/b15850/"},
                       {"id": 15852, "name": "金融街", "url": "http://bj.meituan.com/meishi/b15852/"},
                       {"id": 15956, "name": "白纸坊", "url": "http://bj.meituan.com/meishi/b15956/"},
                       {"id": 15957, "name": "和平门", "url": "http://bj.meituan.com/meishi/b15957/"},
                       {"id": 30867, "name": "首都博物馆/莲花池东路", "url": "http://bj.meituan.com/meishi/b30867/"},
                       {"id": 37343, "name": "前门/天坛", "url": "http://bj.meituan.com/meishi/b37343/"},
                       {"id": 38068, "name": "长椿街", "url": "http://bj.meituan.com/meishi/b38068/"}]},
         {"id": 15, "name": "东城区", "url": "http://bj.meituan.com/meishi/b15/",
          "subAreas": [{"id": 15, "name": "全部", "url": "http://bj.meituan.com/meishi/b15/"},
                       {"id": 1161, "name": "东直门", "url": "http://bj.meituan.com/meishi/b1161/"},
                       {"id": 680, "name": "安定门", "url": "http://bj.meituan.com/meishi/b680/"},
                       {"id": 1483, "name": "和平里", "url": "http://bj.meituan.com/meishi/b1483/"},
                       {"id": 1764, "name": "沙子口", "url": "http://bj.meituan.com/meishi/b1764/"},
                       {"id": 703, "name": "崇文门", "url": "http://bj.meituan.com/meishi/b703/"},
                       {"id": 677, "name": "王府井/东单", "url": "http://bj.meituan.com/meishi/b677/"},
                       {"id": 704, "name": "天坛", "url": "http://bj.meituan.com/meishi/b704/"},
                       {"id": 679, "name": "东四", "url": "http://bj.meituan.com/meishi/b679/"},
                       {"id": 681, "name": "朝阳门", "url": "http://bj.meituan.com/meishi/b681/"},
                       {"id": 678, "name": "建国门/北京站", "url": "http://bj.meituan.com/meishi/b678/"},
                       {"id": 1215, "name": "东四十条", "url": "http://bj.meituan.com/meishi/b1215/"},
                       {"id": 1482, "name": "广渠门", "url": "http://bj.meituan.com/meishi/b1482/"},
                       {"id": 1650, "name": "雍和宫", "url": "http://bj.meituan.com/meishi/b1650/"},
                       {"id": 1763, "name": "左安门", "url": "http://bj.meituan.com/meishi/b1763/"},
                       {"id": 5967, "name": "南锣鼓巷", "url": "http://bj.meituan.com/meishi/b5967/"},
                       {"id": 9205, "name": "北新桥/簋街", "url": "http://bj.meituan.com/meishi/b9205/"},
                       {"id": 14092, "name": "崇文门新世界", "url": "http://bj.meituan.com/meishi/b14092/"},
                       {"id": 36214, "name": "王府井/前门", "url": "http://bj.meituan.com/meishi/b36214/"},
                       {"id": 36355, "name": "南锣古巷/鼓楼后海", "url": "http://bj.meituan.com/meishi/b36355/"}]},
         {"id": 4750, "name": "昌平区", "url": "http://bj.meituan.com/meishi/b4750/",
          "subAreas": [{"id": 4750, "name": "全部", "url": "http://bj.meituan.com/meishi/b4750/"},
                       {"id": 4755, "name": "昌平镇", "url": "http://bj.meituan.com/meishi/b4755/"},
                       {"id": 4753, "name": "回龙观", "url": "http://bj.meituan.com/meishi/b4753/"},
                       {"id": 4754, "name": "天通苑", "url": "http://bj.meituan.com/meishi/b4754/"},
                       {"id": 9154, "name": "南口镇", "url": "http://bj.meituan.com/meishi/b9154/"},
                       {"id": 9155, "name": "小汤山镇", "url": "http://bj.meituan.com/meishi/b9155/"},
                       {"id": 9172, "name": "北七家", "url": "http://bj.meituan.com/meishi/b9172/"},
                       {"id": 9174, "name": "沙河", "url": "http://bj.meituan.com/meishi/b9174/"},
                       {"id": 22995, "name": "十三陵水库", "url": "http://bj.meituan.com/meishi/b22995/"},
                       {"id": 28542, "name": "蟒山国家森林公园", "url": "http://bj.meituan.com/meishi/b28542/"},
                       {"id": 28543, "name": "居庸关长城", "url": "http://bj.meituan.com/meishi/b28543/"},
                       {"id": 28544, "name": "小汤山", "url": "http://bj.meituan.com/meishi/b28544/"},
                       {"id": 28545, "name": "明十三陵", "url": "http://bj.meituan.com/meishi/b28545/"}]},
         {"id": 172, "name": "石景山区", "url": "http://bj.meituan.com/meishi/b172/",
          "subAreas": [{"id": 172, "name": "全部", "url": "http://bj.meituan.com/meishi/b172/"},
                       {"id": 1030, "name": "苹果园", "url": "http://bj.meituan.com/meishi/b1030/"},
                       {"id": 1031, "name": "古城/八角", "url": "http://bj.meituan.com/meishi/b1031/"},
                       {"id": 1032, "name": "鲁谷", "url": "http://bj.meituan.com/meishi/b1032/"},
                       {"id": 1771, "name": "模式口", "url": "http://bj.meituan.com/meishi/b1771/"},
                       {"id": 12581, "name": "八大处", "url": "http://bj.meituan.com/meishi/b12581/"}]},
         {"id": 4751, "name": "通州区", "url": "http://bj.meituan.com/meishi/b4751/",
          "subAreas": [{"id": 4751, "name": "全部", "url": "http://bj.meituan.com/meishi/b4751/"},
                       {"id": 4757, "name": "梨园", "url": "http://bj.meituan.com/meishi/b4757/"},
                       {"id": 4758, "name": "新华大街", "url": "http://bj.meituan.com/meishi/b4758/"},
                       {"id": 4756, "name": "新华联", "url": "http://bj.meituan.com/meishi/b4756/"},
                       {"id": 5977, "name": "武夷花园", "url": "http://bj.meituan.com/meishi/b5977/"},
                       {"id": 5978, "name": "九棵树", "url": "http://bj.meituan.com/meishi/b5978/"},
                       {"id": 5979, "name": "通州北苑", "url": "http://bj.meituan.com/meishi/b5979/"},
                       {"id": 5980, "name": "果园", "url": "http://bj.meituan.com/meishi/b5980/"},
                       {"id": 14122, "name": "八里桥", "url": "http://bj.meituan.com/meishi/b14122/"},
                       {"id": 14123, "name": "马驹桥", "url": "http://bj.meituan.com/meishi/b14123/"},
                       {"id": 15823, "name": "次渠", "url": "http://bj.meituan.com/meishi/b15823/"},
                       {"id": 16688, "name": "宋庄", "url": "http://bj.meituan.com/meishi/b16688/"},
                       {"id": 30604, "name": "土桥", "url": "http://bj.meituan.com/meishi/b30604/"},
                       {"id": 38488, "name": "西集", "url": "http://bj.meituan.com/meishi/b38488/"}]},
         {"id": 4752, "name": "大兴区", "url": "http://bj.meituan.com/meishi/b4752/",
          "subAreas": [{"id": 4752, "name": "全部", "url": "http://bj.meituan.com/meishi/b4752/"},
                       {"id": 4759, "name": "亦庄", "url": "http://bj.meituan.com/meishi/b4759/"},
                       {"id": 4760, "name": "旧宫", "url": "http://bj.meituan.com/meishi/b4760/"},
                       {"id": 4761, "name": "黄村", "url": "http://bj.meituan.com/meishi/b4761/"},
                       {"id": 10502, "name": "西红门", "url": "http://bj.meituan.com/meishi/b10502/"},
                       {"id": 34936, "name": "庞各庄", "url": "http://bj.meituan.com/meishi/b34936/"},
                       {"id": 37490, "name": "南苑机场/德茂桥", "url": "http://bj.meituan.com/meishi/b37490/"}]},
         {"id": 708, "name": "顺义区", "url": "http://bj.meituan.com/meishi/b708/",
          "subAreas": [{"id": 708, "name": "全部", "url": "http://bj.meituan.com/meishi/b708/"},
                       {"id": 13194, "name": "顺义城区", "url": "http://bj.meituan.com/meishi/b13194/"},
                       {"id": 13258, "name": "石园", "url": "http://bj.meituan.com/meishi/b13258/"},
                       {"id": 13259, "name": "后沙峪", "url": "http://bj.meituan.com/meishi/b13259/"},
                       {"id": 13260, "name": "天竺", "url": "http://bj.meituan.com/meishi/b13260/"},
                       {"id": 15806, "name": "南彩镇", "url": "http://bj.meituan.com/meishi/b15806/"},
                       {"id": 15807, "name": "马坡牛栏山镇", "url": "http://bj.meituan.com/meishi/b15807/"},
                       {"id": 28528, "name": "莲花山滑雪场", "url": "http://bj.meituan.com/meishi/b28528/"},
                       {"id": 36497, "name": "小汤山/央美博艺艺术馆", "url": "http://bj.meituan.com/meishi/b36497/"},
                       {"id": 36760, "name": "首都机场T3航站楼", "url": "http://bj.meituan.com/meishi/b36760/"},
                       {"id": 37491, "name": "首都机场/机场路", "url": "http://bj.meituan.com/meishi/b37491/"}]},
         {"id": 710, "name": "房山区", "url": "http://bj.meituan.com/meishi/b710/",
          "subAreas": [{"id": 710, "name": "全部", "url": "http://bj.meituan.com/meishi/b710/"},
                       {"id": 13339, "name": "长阳镇", "url": "http://bj.meituan.com/meishi/b13339/"},
                       {"id": 13340, "name": "良乡", "url": "http://bj.meituan.com/meishi/b13340/"},
                       {"id": 18765, "name": "十渡", "url": "http://bj.meituan.com/meishi/b18765/"},
                       {"id": 22923, "name": "孤山寨", "url": "http://bj.meituan.com/meishi/b22923/"},
                       {"id": 25101, "name": "房山城关", "url": "http://bj.meituan.com/meishi/b25101/"},
                       {"id": 25102, "name": "阎村", "url": "http://bj.meituan.com/meishi/b25102/"},
                       {"id": 25103, "name": "窦店", "url": "http://bj.meituan.com/meishi/b25103/"},
                       {"id": 28572, "name": "霞云岭国家森林公园", "url": "http://bj.meituan.com/meishi/b28572/"},
                       {"id": 28577, "name": "云居滑雪场", "url": "http://bj.meituan.com/meishi/b28577/"},
                       {"id": 28584, "name": "仙栖洞", "url": "http://bj.meituan.com/meishi/b28584/"},
                       {"id": 28589, "name": "东湖港", "url": "http://bj.meituan.com/meishi/b28589/"},
                       {"id": 30866, "name": "上方山国家森林公园", "url": "http://bj.meituan.com/meishi/b30866/"},
                       {"id": 37843, "name": "青龙湖", "url": "http://bj.meituan.com/meishi/b37843/"},
                       {"id": 38998, "name": "河北镇", "url": "http://bj.meituan.com/meishi/b38998/"},
                       {"id": 39120, "name": "燕山", "url": "http://bj.meituan.com/meishi/b39120/"}]},
         {"id": 2074, "name": "密云区", "url": "http://bj.meituan.com/meishi/b2074/",
          "subAreas": [{"id": 2074, "name": "全部", "url": "http://bj.meituan.com/meishi/b2074/"},
                       {"id": 18792, "name": "古北口", "url": "http://bj.meituan.com/meishi/b18792/"},
                       {"id": 18796, "name": "桃源仙谷", "url": "http://bj.meituan.com/meishi/b18796/"},
                       {"id": 18799, "name": "司马台长城", "url": "http://bj.meituan.com/meishi/b18799/"},
                       {"id": 22922, "name": "密云水库", "url": "http://bj.meituan.com/meishi/b22922/"},
                       {"id": 24762, "name": "古北水镇", "url": "http://bj.meituan.com/meishi/b24762/"},
                       {"id": 28550, "name": "云蒙山", "url": "http://bj.meituan.com/meishi/b28550/"},
                       {"id": 28569, "name": "金鼎湖滑雪场", "url": "http://bj.meituan.com/meishi/b28569/"},
                       {"id": 28570, "name": "云佛山滑雪场", "url": "http://bj.meituan.com/meishi/b28570/"},
                       {"id": 28571, "name": "白龙潭", "url": "http://bj.meituan.com/meishi/b28571/"},
                       {"id": 28573, "name": "南山滑雪场", "url": "http://bj.meituan.com/meishi/b28573/"},
                       {"id": 31124, "name": "密云县县城", "url": "http://bj.meituan.com/meishi/b31124/"}]},
         {"id": 711, "name": "怀柔区", "url": "http://bj.meituan.com/meishi/b711/",
          "subAreas": [{"id": 711, "name": "全部", "url": "http://bj.meituan.com/meishi/b711/"},
                       {"id": 18788, "name": "慕田峪长城", "url": "http://bj.meituan.com/meishi/b18788/"},
                       {"id": 18789, "name": "青龙峡", "url": "http://bj.meituan.com/meishi/b18789/"},
                       {"id": 19157, "name": "怀柔城区", "url": "http://bj.meituan.com/meishi/b19157/"},
                       {"id": 19158, "name": "雁栖湖", "url": "http://bj.meituan.com/meishi/b19158/"},
                       {"id": 22921, "name": "白河湾", "url": "http://bj.meituan.com/meishi/b22921/"},
                       {"id": 24076, "name": "喇叭沟门白桦林景区", "url": "http://bj.meituan.com/meishi/b24076/"},
                       {"id": 27203, "name": "神堂峪", "url": "http://bj.meituan.com/meishi/b27203/"},
                       {"id": 27613, "name": "莲花池", "url": "http://bj.meituan.com/meishi/b27613/"},
                       {"id": 28553, "name": "红螺寺", "url": "http://bj.meituan.com/meishi/b28553/"},
                       {"id": 28574, "name": "黄花城水长城", "url": "http://bj.meituan.com/meishi/b28574/"},
                       {"id": 28585, "name": "怀北滑雪场", "url": "http://bj.meituan.com/meishi/b28585/"},
                       {"id": 28586, "name": "幽谷深潭", "url": "http://bj.meituan.com/meishi/b28586/"},
                       {"id": 31126, "name": "怀柔经济开发区", "url": "http://bj.meituan.com/meishi/b31126/"},
                       {"id": 38561, "name": "桥梓镇", "url": "http://bj.meituan.com/meishi/b38561/"},
                       {"id": 38827, "name": "庙城", "url": "http://bj.meituan.com/meishi/b38827/"}]},
         {"id": 2075, "name": "延庆区", "url": "http://bj.meituan.com/meishi/b2075/",
          "subAreas": [{"id": 2075, "name": "全部", "url": "http://bj.meituan.com/meishi/b2075/"},
                       {"id": 18766, "name": "八达岭", "url": "http://bj.meituan.com/meishi/b18766/"},
                       {"id": 18790, "name": "龙庆峡", "url": "http://bj.meituan.com/meishi/b18790/"},
                       {"id": 19159, "name": "延庆城区", "url": "http://bj.meituan.com/meishi/b19159/"},
                       {"id": 19160, "name": "康庄", "url": "http://bj.meituan.com/meishi/b19160/"},
                       {"id": 19161, "name": "柳沟", "url": "http://bj.meituan.com/meishi/b19161/"},
                       {"id": 27280, "name": "百里画廊", "url": "http://bj.meituan.com/meishi/b27280/"},
                       {"id": 28530, "name": "康西草原", "url": "http://bj.meituan.com/meishi/b28530/"},
                       {"id": 28552, "name": "玉渡山风景区", "url": "http://bj.meituan.com/meishi/b28552/"},
                       {"id": 30859, "name": "辉煌国际度假区", "url": "http://bj.meituan.com/meishi/b30859/"}]},
         {"id": 709, "name": "门头沟", "url": "http://bj.meituan.com/meishi/b709/",
          "subAreas": [{"id": 709, "name": "全部", "url": "http://bj.meituan.com/meishi/b709/"},
                       {"id": 18906, "name": "门头沟城区", "url": "http://bj.meituan.com/meishi/b18906/"},
                       {"id": 28529, "name": "龙凤山滑雪场", "url": "http://bj.meituan.com/meishi/b28529/"},
                       {"id": 28537, "name": "百花山", "url": "http://bj.meituan.com/meishi/b28537/"},
                       {"id": 28538, "name": "爨底下村", "url": "http://bj.meituan.com/meishi/b28538/"},
                       {"id": 28539, "name": "京西十八潭", "url": "http://bj.meituan.com/meishi/b28539/"},
                       {"id": 28540, "name": "潭柘寺", "url": "http://bj.meituan.com/meishi/b28540/"},
                       {"id": 28541, "name": "妙峰山", "url": "http://bj.meituan.com/meishi/b28541/"},
                       {"id": 37919, "name": "灵山风景区", "url": "http://bj.meituan.com/meishi/b37919/"}]},
         {"id": 2073, "name": "平谷区", "url": "http://bj.meituan.com/meishi/b2073/",
          "subAreas": [{"id": 2073, "name": "全部", "url": "http://bj.meituan.com/meishi/b2073/"},
                       {"id": 19162, "name": "平谷城区", "url": "http://bj.meituan.com/meishi/b19162/"},
                       {"id": 27149, "name": "金海湖", "url": "http://bj.meituan.com/meishi/b27149/"},
                       {"id": 27150, "name": "石林峡", "url": "http://bj.meituan.com/meishi/b27150/"},
                       {"id": 27189, "name": "天云山", "url": "http://bj.meituan.com/meishi/b27189/"},
                       {"id": 28583, "name": "玻璃台", "url": "http://bj.meituan.com/meishi/b28583/"}]},
         [{"id": 149, "name": "芙蓉区", "url": "http://chs.meituan.com/meishi/b149/",
           "subAreas": [{"id": 149, "name": "全部", "url": "http://chs.meituan.com/meishi/b149/"},
                        {"id": 4822, "name": "马王堆", "url": "http://chs.meituan.com/meishi/b4822/"},
                        {"id": 4821, "name": "德政园/杨家山", "url": "http://chs.meituan.com/meishi/b4821/"},
                        {"id": 4823, "name": "五一广场", "url": "http://chs.meituan.com/meishi/b4823/"},
                        {"id": 4824, "name": "袁家岭/火车站", "url": "http://chs.meituan.com/meishi/b4824/"},
                        {"id": 6020, "name": "晚报大道", "url": "http://chs.meituan.com/meishi/b6020/"},
                        {"id": 6026, "name": "湖南农业大学", "url": "http://chs.meituan.com/meishi/b6026/"},
                        {"id": 7161, "name": "八一路", "url": "http://chs.meituan.com/meishi/b7161/"},
                        {"id": 8051, "name": "人民中路/朝阳路/融圣国际", "url": "http://chs.meituan.com/meishi/b8051/"},
                        {"id": 8052, "name": "司门口", "url": "http://chs.meituan.com/meishi/b8052/"},
                        {"id": 8057, "name": "芙蓉广场", "url": "http://chs.meituan.com/meishi/b8057/"},
                        {"id": 8064, "name": "汽车东站", "url": "http://chs.meituan.com/meishi/b8064/"},
                        {"id": 8067, "name": "五里牌", "url": "http://chs.meituan.com/meishi/b8067/"},
                        {"id": 8072, "name": "芙蓉广场", "url": "http://chs.meituan.com/meishi/b8072/"},
                        {"id": 8073, "name": "八一桥", "url": "http://chs.meituan.com/meishi/b8073/"},
                        {"id": 8074, "name": "韭菜园", "url": "http://chs.meituan.com/meishi/b8074/"},
                        {"id": 8077, "name": "省委", "url": "http://chs.meituan.com/meishi/b8077/"},
                        {"id": 9026, "name": "古曲路/浏阳河婚庆文化园", "url": "http://chs.meituan.com/meishi/b9026/"},
                        {"id": 36483, "name": "万家丽国际MALL", "url": "http://chs.meituan.com/meishi/b36483/"}]},
          {"id": 152, "name": "雨花区", "url": "http://chs.meituan.com/meishi/b152/",
           "subAreas": [{"id": 152, "name": "全部", "url": "http://chs.meituan.com/meishi/b152/"},
                        {"id": 4832, "name": "雨花亭", "url": "http://chs.meituan.com/meishi/b4832/"},
                        {"id": 4830, "name": "桂花路/车站南路", "url": "http://chs.meituan.com/meishi/b4830/"},
                        {"id": 4829, "name": "东塘", "url": "http://chs.meituan.com/meishi/b4829/"},
                        {"id": 7164, "name": "左家塘", "url": "http://chs.meituan.com/meishi/b7164/"},
                        {"id": 7168, "name": "红星国际会展中心", "url": "http://chs.meituan.com/meishi/b7168/"},
                        {"id": 7169, "name": "高桥", "url": "http://chs.meituan.com/meishi/b7169/"},
                        {"id": 8063, "name": "汽车南站", "url": "http://chs.meituan.com/meishi/b8063/"},
                        {"id": 8066, "name": "武广高铁", "url": "http://chs.meituan.com/meishi/b8066/"},
                        {"id": 8069, "name": "体育新城", "url": "http://chs.meituan.com/meishi/b8069/"},
                        {"id": 8076, "name": "窑岭/长岭", "url": "http://chs.meituan.com/meishi/b8076/"},
                        {"id": 9019, "name": "识字岭", "url": "http://chs.meituan.com/meishi/b9019/"},
                        {"id": 9025, "name": "喜盈门 /喜乐地", "url": "http://chs.meituan.com/meishi/b9025/"},
                        {"id": 9028, "name": "梓园路/省儿童医院", "url": "http://chs.meituan.com/meishi/b9028/"},
                        {"id": 9029, "name": "民政学院/香樟路", "url": "http://chs.meituan.com/meishi/b9029/"},
                        {"id": 9030, "name": "井湾子", "url": "http://chs.meituan.com/meishi/b9030/"},
                        {"id": 9031, "name": "友阿奥特莱斯", "url": "http://chs.meituan.com/meishi/b9031/"},
                        {"id": 9560, "name": "树木岭", "url": "http://chs.meituan.com/meishi/b9560/"},
                        {"id": 14689, "name": "天际岭", "url": "http://chs.meituan.com/meishi/b14689/"},
                        {"id": 14699, "name": "环保学院/科技职院", "url": "http://chs.meituan.com/meishi/b14699/"},
                        {"id": 19726, "name": "运达中央广场", "url": "http://chs.meituan.com/meishi/b19726/"},
                        {"id": 25094, "name": "德思勤城市广场", "url": "http://chs.meituan.com/meishi/b25094/"},
                        {"id": 34708, "name": "人民东路", "url": "http://chs.meituan.com/meishi/b34708/"},
                        {"id": 36482, "name": "保利国际MALL", "url": "http://chs.meituan.com/meishi/b36482/"}]},
          {"id": 151, "name": "天心区", "url": "http://chs.meituan.com/meishi/b151/",
           "subAreas": [{"id": 151, "name": "全部", "url": "http://chs.meituan.com/meishi/b151/"},
                        {"id": 4828, "name": "天心阁", "url": "http://chs.meituan.com/meishi/b4828/"},
                        {"id": 7162, "name": "坡子街", "url": "http://chs.meituan.com/meishi/b7162/"},
                        {"id": 7163, "name": "解放西路", "url": "http://chs.meituan.com/meishi/b7163/"},
                        {"id": 7165, "name": "新开铺", "url": "http://chs.meituan.com/meishi/b7165/"},
                        {"id": 7166, "name": "省政府", "url": "http://chs.meituan.com/meishi/b7166/"},
                        {"id": 7167, "name": "南门口", "url": "http://chs.meituan.com/meishi/b7167/"},
                        {"id": 8055, "name": "贺龙体育场", "url": "http://chs.meituan.com/meishi/b8055/"},
                        {"id": 8056, "name": "黄土岭", "url": "http://chs.meituan.com/meishi/b8056/"},
                        {"id": 8058, "name": "识字岭", "url": "http://chs.meituan.com/meishi/b8058/"},
                        {"id": 8062, "name": "步行街", "url": "http://chs.meituan.com/meishi/b8062/"},
                        {"id": 8065, "name": "劳动广场/书院路", "url": "http://chs.meituan.com/meishi/b8065/"},
                        {"id": 8068, "name": "摩天轮", "url": "http://chs.meituan.com/meishi/b8068/"},
                        {"id": 8071, "name": "人民西路口", "url": "http://chs.meituan.com/meishi/b8071/"},
                        {"id": 8075, "name": "浦沅", "url": "http://chs.meituan.com/meishi/b8075/"},
                        {"id": 9017, "name": "铁道学院/林科大", "url": "http://chs.meituan.com/meishi/b9017/"},
                        {"id": 9020, "name": "天虹", "url": "http://chs.meituan.com/meishi/b9020/"},
                        {"id": 9176, "name": "侯家塘", "url": "http://chs.meituan.com/meishi/b9176/"},
                        {"id": 9244, "name": "定王台", "url": "http://chs.meituan.com/meishi/b9244/"},
                        {"id": 34832, "name": "中海环宇城", "url": "http://chs.meituan.com/meishi/b34832/"},
                        {"id": 36481, "name": "悦方ID mall", "url": "http://chs.meituan.com/meishi/b36481/"},
                        {"id": 36738, "name": "云塘理工/环保科技园", "url": "http://chs.meituan.com/meishi/b36738/"}]},
          {"id": 150, "name": "开福区", "url": "http://chs.meituan.com/meishi/b150/",
           "subAreas": [{"id": 150, "name": "全部", "url": "http://chs.meituan.com/meishi/b150/"},
                        {"id": 4825, "name": "四方坪", "url": "http://chs.meituan.com/meishi/b4825/"},
                        {"id": 4827, "name": "伍家岭/开福寺", "url": "http://chs.meituan.com/meishi/b4827/"},
                        {"id": 6019, "name": "中山亭/乐和城", "url": "http://chs.meituan.com/meishi/b6019/"},
                        {"id": 6021, "name": "松桂园", "url": "http://chs.meituan.com/meishi/b6021/"},
                        {"id": 6022, "name": "湘江世纪城", "url": "http://chs.meituan.com/meishi/b6022/"},
                        {"id": 6023, "name": "湘雅附一医院", "url": "http://chs.meituan.com/meishi/b6023/"},
                        {"id": 6024, "name": "烈士公园", "url": "http://chs.meituan.com/meishi/b6024/"},
                        {"id": 7463, "name": "五一广场", "url": "http://chs.meituan.com/meishi/b7463/"},
                        {"id": 8060, "name": "世界之窗/国际会展中心", "url": "http://chs.meituan.com/meishi/b8060/"},
                        {"id": 8070, "name": "月湖公园/长沙大学", "url": "http://chs.meituan.com/meishi/b8070/"},
                        {"id": 9016, "name": "开福万达广场", "url": "http://chs.meituan.com/meishi/b9016/"},
                        {"id": 9087, "name": "珠江花城/万国城", "url": "http://chs.meituan.com/meishi/b9087/"},
                        {"id": 36484, "name": "泊富国际广场", "url": "http://chs.meituan.com/meishi/b36484/"}]},
          {"id": 153, "name": "岳麓区", "url": "http://chs.meituan.com/meishi/b153/",
           "subAreas": [{"id": 153, "name": "全部", "url": "http://chs.meituan.com/meishi/b153/"},
                        {"id": 6027, "name": "溁湾镇/岳麓山", "url": "http://chs.meituan.com/meishi/b6027/"},
                        {"id": 6028, "name": "岳麓大学城", "url": "http://chs.meituan.com/meishi/b6028/"},
                        {"id": 6029, "name": "汽车西站/达美D6区", "url": "http://chs.meituan.com/meishi/b6029/"},
                        {"id": 7007, "name": "橘子洲公园", "url": "http://chs.meituan.com/meishi/b7007/"},
                        {"id": 7534, "name": "商学院/人人乐", "url": "http://chs.meituan.com/meishi/b7534/"},
                        {"id": 7723, "name": "市政府", "url": "http://chs.meituan.com/meishi/b7723/"},
                        {"id": 7776, "name": "奥克斯广场", "url": "http://chs.meituan.com/meishi/b7776/"},
                        {"id": 8059, "name": "麓谷", "url": "http://chs.meituan.com/meishi/b8059/"},
                        {"id": 8061, "name": "观沙岭/茶子山", "url": "http://chs.meituan.com/meishi/b8061/"},
                        {"id": 8953, "name": "含浦", "url": "http://chs.meituan.com/meishi/b8953/"},
                        {"id": 9015, "name": "涉外经济学院", "url": "http://chs.meituan.com/meishi/b9015/"},
                        {"id": 37674, "name": "梅溪湖", "url": "http://chs.meituan.com/meishi/b37674/"},
                        {"id": 37675, "name": "青山镇/莱茵城", "url": "http://chs.meituan.com/meishi/b37675/"},
                        {"id": 37700, "name": "财经学院/西湖公园", "url": "http://chs.meituan.com/meishi/b37700/"},
                        {"id": 37701, "name": "渔人码头", "url": "http://chs.meituan.com/meishi/b37701/"},
                        {"id": 37702, "name": "润泽园", "url": "http://chs.meituan.com/meishi/b37702/"},
                        {"id": 37703, "name": "银盆南路", "url": "http://chs.meituan.com/meishi/b37703/"},
                        {"id": 37704, "name": "金茂览秀城", "url": "http://chs.meituan.com/meishi/b37704/"},
                        {"id": 37705, "name": "月亮岛", "url": "http://chs.meituan.com/meishi/b37705/"},
                        {"id": 37706, "name": "郭亮中路", "url": "http://chs.meituan.com/meishi/b37706/"},
                        {"id": 37707, "name": "正荣广场", "url": "http://chs.meituan.com/meishi/b37707/"},
                        {"id": 37725, "name": "步步高梅溪新天地", "url": "http://chs.meituan.com/meishi/b37725/"},
                        {"id": 37726, "name": "河西王府井/步步高", "url": "http://chs.meituan.com/meishi/b37726/"},
                        {"id": 38360, "name": "雷锋镇", "url": "http://chs.meituan.com/meishi/b38360/"},
                        {"id": 38365, "name": "湘雅附三/肿瘤医院", "url": "http://chs.meituan.com/meishi/b38365/"}]},
          {"id": 3493, "name": "望城区", "url": "http://chs.meituan.com/meishi/b3493/",
           "subAreas": [{"id": 3493, "name": "全部", "url": "http://chs.meituan.com/meishi/b3493/"},
                        {"id": 20717, "name": "望城步行街", "url": "http://chs.meituan.com/meishi/b20717/"},
                        {"id": 20723, "name": "太平洋服饰广场", "url": "http://chs.meituan.com/meishi/b20723/"},
                        {"id": 36943, "name": "正荣财富中心", "url": "http://chs.meituan.com/meishi/b36943/"},
                        {"id": 37381, "name": "长沙医学院", "url": "http://chs.meituan.com/meishi/b37381/"},
                        {"id": 38995, "name": "滨水新城", "url": "http://chs.meituan.com/meishi/b38995/"}]},
          {"id": 3494, "name": "宁乡县", "url": "http://chs.meituan.com/meishi/b3494/",
           "subAreas": [{"id": 3494, "name": "全部", "url": "http://chs.meituan.com/meishi/b3494/"},
                        {"id": 12349, "name": "沿江风光带外滩", "url": "http://chs.meituan.com/meishi/b12349/"},
                        {"id": 12350, "name": "春城万象/步行街", "url": "http://chs.meituan.com/meishi/b12350/"},
                        {"id": 12351, "name": "南站", "url": "http://chs.meituan.com/meishi/b12351/"},
                        {"id": 12352, "name": "东站", "url": "http://chs.meituan.com/meishi/b12352/"},
                        {"id": 12353, "name": "人人乐", "url": "http://chs.meituan.com/meishi/b12353/"},
                        {"id": 12422, "name": "灰汤温泉镇", "url": "http://chs.meituan.com/meishi/b12422/"},
                        {"id": 12651, "name": "一环北路", "url": "http://chs.meituan.com/meishi/b12651/"},
                        {"id": 17337, "name": "豪德", "url": "http://chs.meituan.com/meishi/b17337/"},
                        {"id": 17339, "name": "金洲大道/一中", "url": "http://chs.meituan.com/meishi/b17339/"},
                        {"id": 17341, "name": "大润发", "url": "http://chs.meituan.com/meishi/b17341/"},
                        {"id": 26795, "name": "玉潭镇", "url": "http://chs.meituan.com/meishi/b26795/"},
                        {"id": 37540, "name": "黄材旅游区", "url": "http://chs.meituan.com/meishi/b37540/"}]},
          {"id": 3491, "name": "浏阳市", "url": "http://chs.meituan.com/meishi/b3491/",
           "subAreas": [{"id": 3491, "name": "全部", "url": "http://chs.meituan.com/meishi/b3491/"},
                        {"id": 9525, "name": "永安镇", "url": "http://chs.meituan.com/meishi/b9525/"},
                        {"id": 15561, "name": "浏阳工业园", "url": "http://chs.meituan.com/meishi/b15561/"},
                        {"id": 15566, "name": "天马路/将军路", "url": "http://chs.meituan.com/meishi/b15566/"},
                        {"id": 15569, "name": "行政中心", "url": "http://chs.meituan.com/meishi/b15569/"},
                        {"id": 15570, "name": "淮川街道", "url": "http://chs.meituan.com/meishi/b15570/"},
                        {"id": 15571, "name": "集里街道", "url": "http://chs.meituan.com/meishi/b15571/"},
                        {"id": 15954, "name": "大瑶镇", "url": "http://chs.meituan.com/meishi/b15954/"},
                        {"id": 18488, "name": "洞阳镇", "url": "http://chs.meituan.com/meishi/b18488/"}]},
          {"id": 154, "name": "近郊", "url": "http://chs.meituan.com/meishi/b154/",
           "subAreas": [{"id": 154, "name": "全部", "url": "http://chs.meituan.com/meishi/b154/"}]},
          {"id": 5894, "name": "长沙县", "url": "http://chs.meituan.com/meishi/b5894/",
           "subAreas": [{"id": 5894, "name": "全部", "url": "http://chs.meituan.com/meishi/b5894/"},
                        {"id": 9035, "name": "大众传媒", "url": "http://chs.meituan.com/meishi/b9035/"},
                        {"id": 9036, "name": "泉塘/星城国际", "url": "http://chs.meituan.com/meishi/b9036/"},
                        {"id": 9037, "name": "筑梦园/中南汽车世界", "url": "http://chs.meituan.com/meishi/b9037/"},
                        {"id": 9038, "name": "星沙一桥", "url": "http://chs.meituan.com/meishi/b9038/"},
                        {"id": 9040, "name": "星沙通程广场", "url": "http://chs.meituan.com/meishi/b9040/"},
                        {"id": 10429, "name": "黄花镇/黄花机场", "url": "http://chs.meituan.com/meishi/b10429/"},
                        {"id": 10430, "name": "城西安置小区", "url": "http://chs.meituan.com/meishi/b10430/"},
                        {"id": 17001, "name": "暮云镇", "url": "http://chs.meituan.com/meishi/b17001/"},
                        {"id": 17002, "name": "榔梨镇", "url": "http://chs.meituan.com/meishi/b17002/"},
                        {"id": 36479, "name": "黄兴镇", "url": "http://chs.meituan.com/meishi/b36479/"},
                        {"id": 36480, "name": "华润万象汇", "url": "http://chs.meituan.com/meishi/b36480/"}]}]]'''

results = re.findall('"(http://.*?.meituan.com/meishi/b\d+/)"', areas)  # 针对不同的城市都可提取出来

print(results)
