import pymysql
from twisted.enterprise import adbapi
from twisted.internet import reactor


def go_insert(cursor, sql):
    # 对数据库进行插入操作，并不需要commit，twisted会自动帮我commit
    try:
        sql_list = [
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("酷袋科技 ","游戏产品开发商","文化娱乐","上海","2016-03-17","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("佑尚家居 ","欧洲高端床具制造商","房地产","上海","2016-03-01","天使轮","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("IN Show ","虚拟试衣解决方案提供商","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("VR实验课 ","VR智慧教学系统","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("九鸣技术 ","None","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("魅秀网 ","None","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("哒嗒网络 ","None","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海置森数码技术有限公司 ","数字图像创意及软硬件集成服务商","企业服务","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海厚斯电子科技有限公司 ","一款让您轻松远离颈椎不适的健康热敷环","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海睿君智能科技 ","None","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Yesmylab研朗科学 ","None","VRAR","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("新浪视觉 ","计算机视觉及人工智能大数据研发商","人工智能","上海","2018-01-27","Pre-A轮","600万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("猎萝卜 ","智能猎头招聘平台","人工智能","上海","2017-11-30","天使轮","1亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("元趣信息 ","儿童早教机器人研发商","人工智能","上海","2017-11-27","B轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("指间营销 ","移动大数据营销平台","大数据","上海","2017-10-11","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("中研宏科 ","公司的主营业务是为政府及相关政务部门、科研机构提供智慧政务领域的软件技术开发、解决方案及技术运维服务","人工智能","上海","2017-07-13","新三板定增","1200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("星环科技 ","数据库软件的研发与服务商","大数据","上海","2017-05-04","C轮","2.35亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("DeepTech ","科技媒体","文化娱乐","上海","2017-04-10","Pre-A轮","1400万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("数据米铺 ","自动化智能营销服务商","企业服务","上海","2017-04-10","A+轮","3000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("麦腾创投 ","天使投资机构","人工智能","上海","2017-02-21","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Truthvision ","智能视频分析及图像识别技术研发商","人工智能","上海","2016-12-01","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("simplyBrand ","第三方互联网数据服务提供商","人工智能","上海","2016-10-17","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("好买衣 ","网上虚拟试衣平台","人工智能","上海","2016-09-27","B轮","1500万美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("明机器人 ","智能机器人配件产品研发商","机器人","上海","2016-04-01","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("贝尔赛克 ","生物识别科技公司","人工智能","上海","2015-12-25","A轮","4000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("数猎云 ","图形化自助式企业大数据处理分析和可视化云平台","企业服务","上海","2015-11-09","Pre-A轮","200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("云砥信息 ","None","人工智能","上海","2015-11-09","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海奕行 ","视频应用技术与产品研发商","人工智能","上海","2015-03-11","A轮","数百万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海高欣 ","None","大数据","上海","2015-03-01","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("有活 ","个性化招聘平台","人工智能","上海","2014-12-12","天使轮","数百万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Linking5 ","None","企业服务","上海","2014-09-25","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("脉佗 ","None","人工智能","上海","2014-06-23","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("毕甲信息 ","嵌入式技术解决方案服务商","人工智能","上海","2013-10-16","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("临港软件园 ","软件园产业管理平台","企业服务","上海","2013-09-05","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("斧光科技 ","3D打印制造与机器人机器学习研发商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海麦信 ","模块级机器学习物联网终端","智能硬件","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("fatewall非我 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海觉感 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("阳橙信息科技 ","None","大数据","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("小博广告 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("河流书局 ","高质量书籍动筛选推荐内容平台","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("邦邦掌柜 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海汇聚自动化科技有限公司 ","智能全向移载平台泊车机器人","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海光维电力科技有限公司 ","一家光通信网络部署及检测解决方案供应商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("创蒲数字 ","商业公共空间中国传统文化交互式展览展示平台","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("恒浥智能 ","None","机器人","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("显昊科技 ","None","机器人","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("执展实业 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("苍翼网络 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("仙渡机器人 ","None","机器人","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("宽客科技 ","金融衍生品交易软件服务商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("微彩 ","None","金融","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("人工智能共享金融软件 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海微锐智能科技有限公司 ","微锐无人机航拍图像处理系统","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("海旭软件 ","综合网络管理软件提供商","企业服务","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海砼仁环保技术发展有限公司 ","环保低碳道路科技和材料研发生产商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("临测检测 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海济通 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("众加投资管理 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Omni-ID ","自动识别解决方案提供商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("思慧信息 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("双兆减速机 ","None","智能硬件","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("万行科技 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("看看智能 ","人脸识别技术研发商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("美顿孵化 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("金灯台信息 ","None","医疗","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("MyhomeOS ","None","智能硬件","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("匡泰科技 ","None","智能硬件","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("数久信息 ","基于图像处理的 TAM 隧道沉降和横向位移实时监测系统","智能硬件","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("兆芯 ","处理器芯片等集成电路研发商","先进制造","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("慧观网络 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("永麦通信 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("经尔纬数据技术 ","大数据技术研发与服务公司","大数据","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海容卓 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海楚门 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("帮客多方通讯 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("波士科技 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("我要去学车网 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("感兽 ","None","工具类","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海誉甲 ","自动化生产车间一站式防护解决方案提供商","智能硬件","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("优纳医疗 ","病理诊断解决方案提供商","医疗","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("山牧科技 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海佳名 ","None","文化娱乐","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("微谱技术 ","None","企业服务","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("霖石科技 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("云礼信息 ","None","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("灵声科技 ","智能语音技术提供商","人工智能","上海","未披露","未披露","未披露","未披露","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("源惠电气 ","智慧能源管理综合服务商","企业服务","上海","2018-09-10","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("MarcPoint ","智能化品牌营销服务商","大数据","上海","2018-08-23","Pre-A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("微盟 ","微信平台营销推广服务平台","企业服务","上海","2018-08-07","Pre-IPO","3.21亿美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("iWork365 ","移动协作平台","社交","上海","2018-08-07","Pre-IPO","3.21亿美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("墨墨名品 ","银行端移动广告运营商","企业服务","上海","2018-08-01","B轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("职业梦 ","金融行业垂直招聘服务提供商","企业服务","上海","2018-07-23","战略投资","1000万美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("热璞科技 ","数据库软件开发服务提供商","企业服务","上海","2018-06-08","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("指南猫 ","S2B2C赋能型定制旅游平台","旅游","上海","2018-06-01","B轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("团建队长 ","互联网团建培训师整合平台","企业服务","上海","2018-05-29","种子轮","100万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("美管加 ","美业SaaS系统服务商","企业服务","上海","2018-05-25","A轮","5000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("别样红云PMS ","酒店云PMS服务提供商","企业服务","上海","2018-05-23","被收购","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("美味不用等 ","互联网餐厅解决方案提供商","企业服务","上海","2018-05-10","D轮","4亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("观安信息 ","信息数据安全解决方案提供商","企业服务","上海","2018-02-01","B轮","1.3亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("源蚁科技 ","模块化SaaS投资平台","金融","上海","2018-01-26","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("仟寻MoSeeker ","移动招聘解决方案提供商","企业服务","上海","2018-01-05","B轮","1500万美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("猎萝卜 ","智能猎头招聘平台","人工智能","上海","2017-11-30","天使轮","1亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("指间营销 ","移动大数据营销平台","大数据","上海","2017-10-11","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("鸿研物流 ","可循环包装物研发商","传统行业","上海","2017-09-06","C轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("My+ ","无人售货系统","企业服务","上海","2017-08-14","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("艾璀斯 ","市场调查研究和咨询服务提供商","企业服务","上海","2017-08-02","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("517office ","为中国创业者提供以商务中心为核心的企业管家服务平台","企业服务","上海","2017-06-27","天使轮","180万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("驻云科技 ","云计算和大数据产品服务提供商","企业服务","上海","2017-06-08","C轮","1亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("趣拿 ","O2O体验营销服务提供商","企业服务","上海","2017-05-26","C轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("麦广网络 ","移动互联网数据营销服务商","企业服务","上海","2017-05-15","新三板定增","1200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("彩虹律师 ","None","企业服务","上海","2017-05-10","天使轮","800万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("HelloCareer ","None","企业服务","上海","2017-05-10","战略投资","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("星环科技 ","数据库软件的研发与服务商","大数据","上海","2017-05-04","C轮","2.35亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("百大天利 ","None","企业服务","上海","2017-05-02","Pre-A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("樱桃互动 ","婚庆SaaS云服务平台","企业服务","上海","2017-04-30","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("收钱吧 ","一站式移动支付解决方案提供商","企业服务","上海","2017-04-18","B轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("数据米铺 ","自动化智能营销服务商","企业服务","上海","2017-04-10","A+轮","3000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("清源火眼 ","网络大数据研究及应用服务提供商","大数据","上海","2017-02-20","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("源慧信息 ","None","企业服务","上海","2017-01-24","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海天与空广告 ","None","企业服务","上海","2017-01-18","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("捷羿软件 ","None","企业服务","上海","2016-12-23","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("翼火蛇 ","数据安全服务提供商","企业服务","上海","2016-12-21","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("金丘股份 ","金融银行业软件开发服务商","金融","上海","2016-12-15","新三板定增","1.4亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("施蒂芬 ","None","教育","上海","2016-12-09","天使轮","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("信辉科技 ","通信行业解决服务商","企业服务","上海","2016-12-05","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("焦点品牌 ","整合营销咨询、品牌管理综合服务","企业服务","上海","2016-12-01","新三板定增","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("同道 ","自动化移动营销管理平台","企业服务","上海","2016-11-30","Pre-A轮","100万美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("维金 ","互联网金融基础设施服务商","金融","上海","2016-11-01","B轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("TubeMogul ","基于数据分析的视频营销服务商","文化娱乐","上海","2016-11-01","被收购","5.4亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("泰邑广告 ","视频内容生态构架及服务商","企业服务","上海","2016-10-31","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("蚂蚁HR ","人力资源SaaS服务及人事代理服务商","企业服务","上海","2016-10-27","A轮","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("微飞传播 ","None","企业服务","上海","2016-10-26","新三板定增","700万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("毛遂网 ","人才共享大数据平台","企业服务","上海","2016-10-21","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("鸣泰信息 ","为银行等企业的电子商务业务提供移动互联网消费场景运营服务及相关技术开发","企业服务","上海","2016-10-17","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("壁达订货宝 ","针对壁纸行业的软件提供商","企业服务","上海","2016-09-18","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("铂略咨询 ","在线财务税务培训平台","企业服务","上海","2016-09-01","A轮","2200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Adbug ","第三方广告验证公司","企业服务","上海","2016-08-23","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("上海东铸智能科技有限公司 ","None","智能硬件","上海","2016-08-22","天使轮","700万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("电科华云 ","云计算方案提供商和服务商","企业服务","上海","2016-08-18","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("泽鑫科技 ","智能电网自动化领域内相关产品研发商","物联网","上海","2016-08-12","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("旋荣科技 ","None","企业服务","上海","2016-08-11","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("秒工作 ","人力资源外包服务商","企业服务","上海","2016-08-03","被收购","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Persona ","None","企业服务","上海","2016-08-01","种子轮","数十万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("德亚智能 ","None","企业服务","上海","2016-07-29","新三板","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("图畅科技 ","3D图形图像计算开发服务商","企业服务","上海","2016-07-25","B轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("Workface ","创业者开辟交流空间社交平台","社交","上海","2016-07-01","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("玖达 ","建设行业信息化咨询服务解决方案提供商","企业服务","上海","2016-06-01","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("KNOTE智能会议 ","智能会议设备研发制造商","企业服务","上海","2016-05-22","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("八点办 ","企业移动互联解决方案提供商","企业服务","上海","2016-05-17","天使轮","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("源邮科技 ","云办公供应商","企业服务","上海","2016-05-17","天使轮","1000万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("觅优商旅网 ","商旅管理平台","旅游","上海","2016-05-13","B轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("中鋆科技 ","IT综合服务提供商","企业服务","上海","2016-05-01","天使轮","200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("管易云 ","电子商务管理软件开发商","消费","上海","2016-05-01","被收购","2.5亿人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("红领军 ","服务人员招聘平台","企业服务","上海","2016-04-01","天使轮","200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("虫洞金融 ","差旅金融信息服务提供商","企业服务","上海","2016-04-01","Pre-A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("杰康诺 ","酵母加工生产商","消费","上海","2016-03-30","A+轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("奇子金服 ","互联网金融信息服务机构","金融","上海","2016-03-21","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("星站TV ","None","文化娱乐","上海","2016-03-11","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("R&B ","智能建筑管理SAAS平台","企业服务","上海","2016-03-01","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("爱客咨询 ","大数据营销解决方案提供商","企业服务","上海","2016-03-01","天使轮","数百万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("赢了网 ","诉讼交易平台","企业服务","上海","2016-03-01","B轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("超级表格 ","云端数据协作软件","企业服务","上海","2016-02-01","Pre-A轮","300万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("可可空间 ","一站式创业服务提供商","企业服务","上海","2016-01-08","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("微猫 ","None","消费","上海","2016-01-05","A轮","数千万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("后勤小秘书 ","企业后勤采购服务电商平台","消费","上海","2015-12-30","种子轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("中道汽车救援 ","None","汽车交通","上海","2015-11-30","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("全程费控 ","商务消费软件服务提供商","企业服务","上海","2015-11-19","B轮","数千万美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("比技信息 ","物联网解决方案提供商","企业服务","上海","2015-11-11","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("数猎云 ","图形化自助式企业大数据处理分析和可视化云平台","企业服务","上海","2015-11-09","Pre-A轮","200万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("喜报 ","企业商旅报销与费用管控SaaS平台","企业服务","上海","2015-11-01","天使轮","600万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("风行全球送 ","跨境物流解决方案提供商","物流仓储","上海","2015-10-30","A轮","500万人民币","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("浦东科技融资担保 ","中小微企业融资担保机构","企业服务","上海","2015-10-12","A轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("指易 ","自助式公共智能服务终端综合解决方案供应商","企业服务","上海","2015-10-01","天使轮","未披露","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("比菜价 ","蔬菜农副产品B2B交易平台","消费","上海","2015-09-14","A轮","720万美元","None","","","","","","","1","2018-11-29")',
            'INSERT INTO XINIU1129(project_name,brief,industry,city,finance_time,finance,money,agency,legal_person,legal_name,registered_capital,competing_product,past_financing,teams,types,insert_times) VALUES ("数创科技 ","汽车大数据服务提供商","企业服务","上海","2015-09-10","Pre-A轮","2000万人民币","None","","","","","","","1","2018-11-29")']
        for sql in sql_list:
            cursor.execute(sql)
    except Exception as e:
        print(e)


def handle_error(failure):
    # 打印错误
    if failure:
        print(failure)


def mains():
    # 数据库基本配置
    db_settings = {
        'host': '192.168.103.31',
        'db': 'company',
        'user': 'root',
        'password': 'adminadmin',
        'charset': 'utf8',
        'use_unicode': True
    }
    # sql语句
    # insert_sql = insert_sql
    # print('当前入库的语句', insert_sql)
    try:
        # 生成连接池
        db_conn = adbapi.ConnectionPool('pymysql', **db_settings)
        # 通过连接池执行具体的sql操作，返回一个对象
        query = db_conn.runInteraction(go_insert)
        # 对错误信息进行提示处理
        query.addCallbacks(handle_error)
    except Exception as e:
        print(e)

    # 定时，给4秒时间让twisted异步框架完成数据库插入异步操作，没有定时什么都不会做
    reactor.callLater(4, reactor.stop)
    reactor.run()


if __name__ == '__main__':

    mains()
